User:
  name:
    maximum: 50
  email:
    maximum: 255
  password:
    minimum: 6
  time_reset_expired: 2
  show_follow:
    gravatar_size: 30
Micropost:
  picture_size: 5
  maximum_content: 140
  gravatar_size: 50
PictureUploader:
  resize_limit:
    width: 400
    height: 500
UserInfo:
  size_picture: 50
